[ETCM-173] Re-think the timestamp validation rule of checkpoint blocks
input-output-hk/mantis pull request #754
Opened 2020-10-22 14:34 UTC by pslaski

# Description

The goal was to make blocks with checkpoint not included in computing PoW difficulty.

# Proposed Solution

Set block with checkpoint difficulty to zero and in case of having a block with checkpoint as a parent use grandparent difficulty and timestamp gap between grandparent and great grandparent

# Important Changes Introduced

- block with checkpoint has zero difficulty now
- the difficulty and timestamp gap used for computing new difficulty is taken from grandparents when the parent is a block with checkpoint

# Testing

Unit tests

2020-10-23 13:08 UTC, rtkaczyk commented on src/test/scala/io/iohk/ethereum/consensus/validators/BlockHeaderValidatorSpec.scala
> -  it should "properly calculate the difficulty after difficulty bomb resume (with reward reduction)" in new EphemBlockchainTestSetup {
Yes!

2020-10-23 13:10 UTC, rtkaczyk commented on src/main/scala/io/iohk/ethereum/domain/BlockHeader.scala
> +  val EmptyDifficulty: BigInt = BigInt(0)
I'd call it `ZeroDifficulty` (since we're feeding our OCDs 😁 )

2020-10-23 13:14 UTC, rtkaczyk commented on src/main/scala/io/iohk/ethereum/consensus/ethash/difficulty/EthashDifficultyCalculator.scala
> +    val parentHeaderDifficulty = if (!parentHeader.hasCheckpoint) parentHeader.difficulty else grandparentDifficulty
Maybe rename to `ancestorDifficulty`?

2020-10-23 13:18 UTC, rtkaczyk commented on src/main/scala/io/iohk/ethereum/consensus/ethash/difficulty/EthashDifficultyCalculator.scala
> +    lazy val GrandparentsData(grandparentDifficulty, grandparentsTimestampDiff) = grandParentsDataGetter(
Ok, my OCD is breaking through the roof, but I would put everything after `=` on a single new line

2020-10-23 13:23 UTC, rtkaczyk commented
I'm a bit uneasy that we leaped to implementation so quickly. Do we have any numerical analysis that suggests that this idea is in fact better, or that the current way has any practical downsides?

2020-10-23 14:07 UTC, pslaski commented
No, but I can prepare some quasi-test-benchmark to see how the difficulty will change

2020-10-23 17:33 UTC, ntallar requested changes

2020-10-23 17:33 UTC, ntallar commented on src/main/scala/io/iohk/ethereum/consensus/ethash/difficulty/EthashDifficultyCalculator.scala
>          if (blockTimestamp < parentHeader.unixTimestamp + 13) 1 else -1
>parentHeader.unixTimestamp

Should this be adapted as well?

2020-10-23 17:33 UTC, ntallar commented on src/main/scala/io/iohk/ethereum/consensus/ethash/difficulty/EthashDifficultyCalculator.scala
>    def calculateDifficulty(blockNumber: BigInt, blockTimestamp: Long, parentHeader: BlockHeader): BigInt = {
I've been thinking... given this scenario of B1->B2->C3->B4, that we are calculating the difficulty of B4 what would be the difference between:
1. Do as done here that the difficulty of B4 is calculated using the difference in timestamps of B2 and B1
2. Have B4 have the same difficulty as B2

?

Aren't they mostly the same? (if that's so maybe we could go with 2. as it's simpler)

2020-10-23 17:34 UTC, ntallar commented on src/main/scala/io/iohk/ethereum/consensus/ethash/difficulty/EthashDifficultyCalculator.scala
>    def calculateDifficulty(blockNumber: BigInt, blockTimestamp: Long, parentHeader: BlockHeader): BigInt = {
Something else that I noticed and I don't like much is that having the `timestampDiff=B2.timestamp-B1.timestamp` means that it doesn't adapt in any way to a how long B4 takes to mine... I was thinking of something like `(B4.timestamp-B2.timestamp)/2` but it assumes that producing a checkpoint block takes the same time to produce as a regular block. Maybe the best alternative for now is just leave one of the above solutions and re-check that after evaluating the integration with OBFT

2020-11-06 13:26 UTC, pslaski commented
temporarily closed as we decided to first test current calculator on the testnet

2020-11-06 13:26 UTC, closed without merging