[Fix] Non checkpoint blocks after ECIP1098 should have HefPostEcip1097 extra fields
input-output-hk/mantis pull request #762
Opened 2020-10-27 19:37 UTC by ntallar

# Description

_A clear and concise description of what this pull request does or fixes._

# Proposed Solution

_**Optional** Explain how does this PR solves the problem stated in [Description](#Description). You can also enumerate different alternatives considered while approaching this task._

# Important Changes Introduced

_**Optional** Notice Reviewers about changes that were introduced while developing this task_

# Testing

_**Optional** Leave some recommendations should be useful while reviewers are testing this PR_

2020-10-28 13:27 UTC, pslaski approved these changes

2020-10-28 13:39 UTC, pslaski requested changes
I tried the scenario when isECIP1097 is activated, but not isECIP1098 and mocked mined block is not passing a validation. The problem is `validateExtraFields` method which assumes that isECIP1097 is always activated with isECIP1098

2020-10-28 19:18 UTC, ntallar commented
For now ECIP1098 has to always be activated before ECIP1097 and we are assuming for now that that will be the behaviour on any testnet used, as was described here: #709

I'll add a comment on the ECIPs configuration on that assumption

2020-10-29 10:26 UTC, pslaski approved these changes

2020-10-29 13:50 UTC, rtkaczyk approved these changes

2020-10-29 15:07 UTC, merged