WIP [ETCM-396] faucet timeout
input-output-hk/mantis pull request #829
Opened 2020-12-03 15:24 UTC by biandratti

# Description

_A clear and concise description of what this pull request does or fixes._

# Proposed Solution

_**Optional** Explain how does this PR solves the problem stated in [Description](#Description). You can also enumerate different alternatives considered while approaching this task._

# Important Changes Introduced

_**Optional** Notice Reviewers about changes that were introduced while developing this task_

# Testing

_**Optional** Leave some recommendations should be useful while reviewers are testing this PR_

2020-12-03 17:41 UTC, lemastero approved these changes
LGTM 👍  This is a change in config. Probably worth to announce on proper channels.

2020-12-04 15:06 UTC, ntallar requested changes
Minor comment and LGTM! I'll create the corresponding PR on devops side and we'll discuss with them about re-deploying it

2020-12-04 15:15 UTC, biandratti commented on src/main/scala/io/iohk/ethereum/faucet/jsonrpc/FaucetRpcService.scala
> +  implicit lazy val actorTimeout: Timeout = Timeout(config.responseTimeout + config.rpcClient.timeout)
Right, I can change the property too, with the same name “actor-communication-margin”.

2020-12-04 15:40 UTC, biandratti commented on src/main/scala/io/iohk/ethereum/faucet/jsonrpc/FaucetRpcService.scala
> +  implicit lazy val actorTimeout: Timeout = Timeout(config.responseTimeout + config.rpcClient.timeout)
Done

2020-12-04 18:46 UTC, ntallar approved these changes
LGTM!
```
 .\\            //.
. \ \          / /.
.\  ,\     /` /,.-
 -.   \  /'/ /  .
 ` -   `-'  \  -
   '.       /.\`
      -    .-
      :`//.'
      .`.'
      .' BP 
```

2020-12-04 18:47 UTC, merged